### ISSUE TITLE
Create a role for managing only profiles

### ISSUE THREAD

**Issue by gfedorenko** [rubykube/barong#108]
We need a role for accessing only profiles page on admin panel.

**Comment by spavlishak** [comment]
in progress #118

**Comment by rraallvv** [comment]
Hmm... sorry to ask, but where can I access the admin panel?

Already tried https://example.com/admin but I'm redirected to https://example.com

I haven't installed Barong yet nor peatio-trading-ui, and the only authentication option enabled is Google OAuth

**Comment by rraallvv** [comment]
Thanks for the quick reply.

My bad, I'm trying to access the Peatio admin panel and found this issue googling for RubuKube admin panel. I just realized this is a Barong issue.

I'm able to login with my Google account, but haven't installed Barong yet, do I need Barong to access Peatio admin panel?

**Comment by gfedorenko** [comment]
No, you don't need Barong to access Peatio admin panel.
Please, double check in your email is set as admin email in `application.yml`. If yes, you can login with Google and access admin panel via user dropdown menu in the top right corner.

**Comment by rraallvv** [comment]
Wow! Thanks. Now it seems obvious, since I've already modified `application.yml` a couple of times in the installation process. Nevertheless, this could be added to the docs, since that's the first place one search for those kind of things. Thanks again, I appreciate it a lot.

**Comment by gfedorenko** [comment]
@rraallvv 
Sure, no problems)
