### ISSUE TITLE
User has ability to get back to already passed step verification

### ISSUE THREAD

**Issue by mkuvshynnikov** [rubykube/barong#115]
Step to reproduce:
1. Pass the verification to the step - "uploading documents";
2. Get back  to the step "verify your mobile phone" by clicking on browser button "Back"
Actual result:
User has been stuck on step  "verify your mobile phone".
Expected result:
User can not get back to already passed step of verification.

**Comment by gfedorenko** [comment]
It's fine cause Account can have more than one phone
