### ISSUE TITLE
«Some fields are empty or invalid» when submitting KyC

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#136]
<img width="984" alt="screen shot 2018-02-15 at 4 56 40 pm" src="https://user-images.githubusercontent.com/7421323/36262856-4396f770-1271-11e8-8f22-0f76761b23fd.png">

**Comment by gfedorenko** [comment]
Already fixed this
Latest master: 
![screenshot from 2018-02-15 17-28-20](https://user-images.githubusercontent.com/25289193/36264574-c121e37c-1275-11e8-8ed1-8ba167dc8032.png)

**Comment by arruah** [comment]
How did you fix it?
