### ISSUE TITLE
Fix issue with unlocking account

### ISSUE THREAD

**Issue by gfedorenko** [rubykube/barong#147]

**Comment by andreymakovenko** [comment]
![checklocally](https://user-images.githubusercontent.com/15743844/36431985-b68f524c-1661-11e8-9f89-2cc39e90462a.png)
![screenshot-2018-2-20 unlock instructions - amakovenko heliostech fr - helios technologies mail](https://user-images.githubusercontent.com/15743844/36432007-c523548e-1661-11e8-972e-c49ebf116bc5.png)

Works locally and online from account.coinfield.work for me, I'm attaching the proof screenshots. 
I think issue can be closed for now.

**Comment by gfedorenko** [comment]
@andreymakovenko Okay. Thank you

**Comment by gfedorenko** [comment]
![deepinscreenshot_select-area_20180221154519](https://user-images.githubusercontent.com/25289193/36485886-e538ac50-1725-11e8-9fde-75bc3235660a.png)
