### ISSUE TITLE
2FA signing service specs

### ISSUE THREAD

**Issue by mod** [rubykube/barong#151]
## OTP Sign in management api

Abiltity to receive and sign a JSON object if the otp code is valid

AppLogic 
```
{
  uid: 'ID4242',
  otp: 432567,
  payload: "BASE64_ENCODED_JSON_OBJECT"
}
```
Validation steps:
1- Check UID exist
2- Check if otp is valid
3- Check base64 is valid
4- Check if payload is valid json after decoding

DO:
- Sign the payload and return an RFC 7516 full json object using multi-sig-jwt gem

Validates otp for user(uid) and sign the payload with a JWT and 
returns it a structure like:
```
     {
      "payload":
       "eyJpc3MiOiJqb2UiLA0KICJleHAiOjEzMDA4MTkzODAsDQogImh0dHA6Ly9leGF
        tcGxlLmNvbS9pc19yb290Ijp0cnVlfQ",
      "signatures":[
       {"protected":"eyJhbGciOiJSUzI1NiJ9",
        "header":
         {"kid":"2010-12-29"},
        "signature":
         "cC4hiUPoj9Eetdgtv3hF80EGrhuB__dzERat0XF9g2VtQgr9PJbu3XOiZj5RZ
          mh7AAuHIm4Bh-0Qc_lF5YKt_O8W2Fp5jujGbds9uJdbF9CUAr7t1dnZcAcQjb
          KBYNX4BAynRFdiuB--f_nZLgrnbyTyWzO75vRK5h6xBArLIARNPvkSjtQBMHl
          b1L07Qe7K0GarZRmB_eSN9383LcOLn6_dO--xi12jzDwusC-eOkHWEsqtFZES
          c6BfI7noOPqvhJ1phCnvWh6IeYI2w9QOYEUipUTI8np6LbgGY9Fs98rqVt5AX
          LIhWkWywlVmtVrBp0igcN_IoypGlUPQGe77Rw"},
       {"protected":"eyJhbGciOiJFUzI1NiJ9",
        "header":
         {"kid":"e9bc097a-ce51-4036-9562-d2ade882db0d"},
        "signature":
         "DtEhU3ljbEg8L38VWAfUAqOyKAM6-Xx-F4GawxaepmXFCgfTjDxw5djxLa8IS
          lSApmWQxfKTUJqPP3-Kg6NU1Q"}]
     }
```

**Comment by dutchakdev** [comment]
Hey! Mb just use secret key for signing request?
I mean: External system has middleware which send request to barong on route 
`POST /api/v1/security/otpsign` with payload uid and code and sign that request with secret key (for ex used hmac)

I mean, jwt not required for that task, what you think?

**Comment by dutchakdev** [comment]
I thought and think you idea will be better, because jwt can be most compact.

**Comment by mod** [comment]
@dutchakdev 
yes using JWT we use the RSA256 private key to sign the payload with an otp verification

**Comment by maksim-litvinov** [comment]
Implemented
