### ISSUE TITLE
Input Authenticator Page

### ISSUE THREAD

**Issue by planbkiev** [rubykube/barong#152]
@spavlishak 
Please find here screen "Barong Authenticator Code 2":
https://zpl.io/V0MGqwO

![barong_authenticator_icon 2](https://user-images.githubusercontent.com/35262194/36423898-3e90425e-164a-11e8-991e-84b203cc40f9.png)
![barong_authenticator_icon](https://user-images.githubusercontent.com/35262194/36423900-3eb0c25e-164a-11e8-97b2-9851216206f8.png)
![barong authenticator code 2a](https://user-images.githubusercontent.com/35262194/36423910-45573214-164a-11e8-83d2-fb692c906cea.png)

**Comment by amir-budaychiev** [comment]
@spavlishak You can close that issue, PR already is closed
