### ISSUE TITLE
Make admin panel fixes

### ISSUE THREAD

**Issue by amir-budaychiev** [rubykube/barong#160]
Admin panel fixes:
1) Fixes regarding with tables styles;
2) Fixes regarding with redirecting in the application page;
3) Fixes regarding with notifications styles;

![image 2018-02-20 09-49-01](https://user-images.githubusercontent.com/18741128/36481732-c21e8464-1721-11e8-8e86-d62ad7d6eb7e.png)
![barong admin 2018-02-20 10-42-15](https://user-images.githubusercontent.com/18741128/36481777-de7d087e-1721-11e8-880c-d2b4a4dc53ba.png)
![image 2018-02-19 17-52-30](https://user-images.githubusercontent.com/18741128/36481791-eb7b0e68-1721-11e8-9573-c0f415cc9372.png)
![image 2018-02-21 14-28-23](https://user-images.githubusercontent.com/18741128/36481798-f44cff56-1721-11e8-969c-dd65826e4583.png)

**Comment by spavlishak** [comment]
in progress #165
