### ISSUE TITLE
ActionView::Template::Error (couldn't find file 'dropify/src/js/dropify' with type 'application/javascript'

### ISSUE THREAD

**Issue by umaimehm** [rubykube/barong#189]
I guess one has to seperately download Dropify.
But where should this be placed for the application to pick it up?

I tried downloading dropify from https://github.com/JeremyFagis/dropify
placed it in the repo of barong but it still didnt pick up dropify.
Can you please advice.

**Comment by umaimehm** [comment]
just to point out, I am running barong outside peatio as an independent application

**Comment by gfedorenko** [comment]
@umaimehm Hi) Try running  ``` yarn install ```
