### ISSUE TITLE
Ability to manage trading tokens from barong

### ISSUE THREAD

**Issue by mod** [rubykube/barong#211]
As a user I want to access a barong api where I can create, delete tokens and configure api tokens.

call it /api/v1/keypairs
CRUD

user can create read update delete

We need a page for example security/keys
in which you can create a new api key
form is

## Schema

- name
- key: ~20 chars
- secret: ~40 chars
- scopes: space separated scopes (strings) oauth scopes "peatio:trade"
- lifetime: number of second each JWT will live for, between 10 sec and 7200 sec
- timestamps

```python
import hmac
import hashlib

message = nonce + customer_id + api_key
signature = hmac.new(
    API_SECRET,
    msg=message,
    digestmod=hashlib.sha256
).hexdigest().upper()
```

Additional feature for later
<img width="638" alt="screen shot 2018-04-18 at 17 47 28" src="https://user-images.githubusercontent.com/80003/38939531-c8c7ec70-4330-11e8-997e-933223487e7e.png">

**Comment by amir-budaychiev** [comment]
@mod how to name the model? and let's clarify which fields will be available?
