### ISSUE TITLE
Missing assets at /documents/new

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#221]
![image](https://user-images.githubusercontent.com/7421323/36976730-4dea0b26-2087-11e8-937b-f82a98ef89b5.png)

![image](https://user-images.githubusercontent.com/7421323/36973083-3440d82e-207a-11e8-9c69-6242803c6907.png)

**Comment by amir-budaychiev** [comment]
@yivo That's solved. Please, check from master branch.

**Comment by gfedorenko** [comment]
Icon was deleted by #196
