### ISSUE TITLE
Document form doesn't work with valid data

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#224]
<img width="549" alt="2018-03-05--13-39-52" src="https://user-images.githubusercontent.com/7421323/36973236-d1015594-207a-11e8-9243-9c8204c76d8a.png">

<img width="571" alt="2018-03-05--13-39-57" src="https://user-images.githubusercontent.com/7421323/36973242-d463ff66-207a-11e8-823f-8f76dddb4188.png">

**Comment by amir-budaychiev** [comment]
@yivo @gfedorenko That's solved. Please, check from master branch.

**Comment by gfedorenko** [comment]
Issue related to minimum file size and was closed by #199
