### ISSUE TITLE
Markup & CSS issue: page is jumping, very ugly

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#226]
https://youtu.be/WN4qEw4mZUk

**Comment by amir-budaychiev** [comment]
@yivo @gfedorenko After reloading this page about some times and trying to catch this problem - it's just not jumping for me.
Please, try that again on master branch.

**Comment by yivo** [comment]
@amir-budaychiev @gfedorenko Still on master. Please, check again and fix.

**Comment by amir-budaychiev** [comment]
@yivo I recorded screencast regarding this problem
link:https://drive.google.com/open?id=1l-U8PNTwgj4Pn4-mx6irly4fL-D_0cK-
it works fine for me
