### ISSUE TITLE
I can't upload files with UPPERCASE extension

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#235]

**Comment by yivo** [comment]
![image](https://user-images.githubusercontent.com/7421323/36985794-e01b4b9a-20a0-11e8-87b4-c57419101f3a.png)

**Comment by amir-budaychiev** [comment]
@yivo @gfedorenko I uploaded files with uppercase extensions.
No errors found. It's just uploaded. You can see screenshots:
![barong admin 2018-03-06 14-29-56](https://user-images.githubusercontent.com/18741128/37030230-484881ce-214b-11e8-9975-bd0bb2d26aa4.png)

**Comment by yivo** [comment]
@amir-budaychiev @gfedorenko It doesn't worked for me. I use latests of OS X and Chrome.

**Comment by yivo** [comment]
It doesn't allow to select UPPERCASE files in file window.

**Comment by amir-budaychiev** [comment]
@yivo can you record a screencast to fully determine the problem?

**Comment by amir-budaychiev** [comment]
@yivo do you use the project with latest version from master branch?

**Comment by amir-budaychiev** [comment]
@yivo I recorded a video in which I adding files with UPPERCASE extension. 
Link: https://drive.google.com/open?id=1ZIwcFLFBWCvFogMgignXFjRdyWLvlfFM
As you see it's fully ok

**Comment by amir-budaychiev** [comment]
@yivo I've rechecked that again via MacBook Air:
![barong admin 2018-03-12 21-52-38](https://user-images.githubusercontent.com/18741128/37303797-9c8b302a-2640-11e8-8675-4f0434166f0c.png)
It works fine. 
So, in the previous time I've checked that via Mac Mini, so it's worked fine too.

**Comment by amir-budaychiev** [comment]
@gfedorenko Can we close that issue?
