### ISSUE TITLE
If I submit second document after approval of first it is not displayed in admin panel 

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#236]
![image](https://user-images.githubusercontent.com/7421323/36985851-0ae5af3c-20a1-11e8-87dc-38c748c46708.png)

**Comment by amir-budaychiev** [comment]
@yivo @gfedorenko I added the documents as you said, they are displaying for me
![barong admin 2018-03-06 15-11-39](https://user-images.githubusercontent.com/18741128/37032786-be5f2db4-2154-11e8-843f-6db3d474266e.png)

**Comment by amir-budaychiev** [comment]
@yivo In this screencast I submit second document after approval of first
Link: https://drive.google.com/open?id=1ZIwcFLFBWCvFogMgignXFjRdyWLvlfFM 
it is displayed in admin panel

**Comment by amir-budaychiev** [comment]
@yivo I rechecked that via MacBook Air - it works correctly. In the previous time I've checked that via Mac Mini.
It works in the right way on both devices.
