### ISSUE TITLE
I scanned QR for 2FA. What's next?

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#237]
![image](https://user-images.githubusercontent.com/7421323/36985921-437c526a-20a1-11e8-8f66-502b5ce2b049.png)

**Comment by ashanaakh** [comment]
#205

**Comment by yivo** [comment]
@ashanaakh @gfedorenko I scanned QR code. What's next?

![image](https://user-images.githubusercontent.com/7421323/37038514-a5ae7e38-215d-11e8-9492-529930c25e92.png)

**Comment by maksim-litvinov** [comment]
will be fixed soon. I'm working on it
