### ISSUE TITLE
It is possible to set any state for account & profile

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#240]
![image](https://user-images.githubusercontent.com/7421323/36987894-1ab9dae6-20a6-11e8-8aeb-17868c1efb3e.png)

![image](https://user-images.githubusercontent.com/7421323/36987902-1fb9fbf2-20a6-11e8-8381-6e02247f0efb.png)

**Comment by amir-budaychiev** [comment]
@yivo @gfedorenko Having logged in under 'admin' you can change ROLE of Account and STATE of Profile, being the 'compliance' you have the opportunity to change the STATE of Profile.
![barong admin 2018-03-06 14-42-03](https://user-images.githubusercontent.com/18741128/37030679-e53b7cc4-214c-11e8-99bc-38c224e3c137.png)

**Comment by yivo** [comment]
@amir-budaychiev It is possible to set any state I want. This is the issue.

**Comment by amir-budaychiev** [comment]
@yivo Need we start defining states and events together with their transitions? So we can set some scenario via gem AASM.

@gfedorenko what do you think?
