### ISSUE TITLE
Adding 2FA auth. with Google Auth.

### ISSUE THREAD

**Issue by mod** [rubykube/barong#25]
Once a user verified his phone with a 2FA,
he can activate 2FA with Google Auth.

We need to generate a seed for TOTP with a QR code
The user needs to scan or enter the seed
We need to ask him to clearly write down the seed on a piece of paper.

Then user can enter a 2FA code and it should activate the 2FA.

**Comment by ashanaakh** [comment]
Working on it #72

**Comment by gfedorenko** [comment]
Closed by #78
