### ISSUE TITLE
Extremely difficult to understand UID, use email instead

### ISSUE THREAD

**Issue by ashanaakh** [rubykube/barong#258]
https://github.com/rubykube/barong/blob/b826730091d82e50f75a6415bdf01b925f9c2133/lib/vault/totp.rb#L33

@dkkoval Can you please fix this ?
Also I need ability to specify issuer name with ENV.

**Comment by ashanaakh** [comment]
@dkkoval Can you please fix this ?

**Comment by ashanaakh** [comment]
Also I need ability to specify issuer name with ENV.

**Comment by dkkoval** [comment]
@ashanaakh you're late 😛 , there's already a fix: #257

**Comment by ashanaakh** [comment]
Oh sorry, thanks 😄
