### ISSUE TITLE
Add API calls to manage user documents

### ISSUE THREAD

**Issue by calj** [rubykube/barong#275]
- Upload a new document
- List uploaded documents with status
- Display a raw document (we need to think about supported formats)

**Comment by mod** [comment]
Agreed

**Comment by Namresiac** [comment]
+ a review of all previous log-in times please
![screenshot from 2018-03-26 13-21-42](https://user-images.githubusercontent.com/22836830/37903592-c2877d0c-30f8-11e8-9d64-09907160f41b.png)
