### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by top1st** [rubykube/barong#289]
when i confirm the signup email getting this error.

![image](https://user-images.githubusercontent.com/23559697/37849942-8159c3b6-2f14-11e8-8ed5-227a3ab1fe48.png)

**Comment by gfedorenko** [comment]
Hello @top1st 

The vault server is not running or was configured in a wrong way.
Please, read this issue https://github.com/rubykube/barong/issues/252
You might find the answer there

**Comment by top1st** [comment]
@gfedorenko 
I have done your suggest but still getting same error

**Comment by top1st** [comment]
i used stable-version 1.5
![image](https://user-images.githubusercontent.com/23559697/37860178-1b249066-2f5b-11e8-8196-77c2053ccc3a.png)

**Comment by gfedorenko** [comment]
@top1st  the error is not the same. You get "permission denied" from the vault server. 
We'll do a patch disabling 2fa if you don't have vault running and configured. 

As for now, you can just replace this line with ```false```  and it should work

**Comment by andreymakovenko** [comment]
Hello, @top1st 
Vault server denies your connection to totp engine. You have probably forgot to pass your vault token to VAULT TOKEN env variable, or you have forgot to enable totp

**Comment by top1st** [comment]
Now all works but in dev mode the email not sent to my email address and phone sms not sending

![image](https://user-images.githubusercontent.com/23559697/37875040-4b4632b0-306c-11e8-8fd9-c435103643c7.png)

The mail catcher seems have sent email but i cannot get in my email and sms

It seems problem in my config smtp and twilio config

![image](https://user-images.githubusercontent.com/23559697/37875058-90d91752-306c-11e8-85ac-9e30440f4af3.png)


/config/charts/barong/values.yaml

@gfedorenko  could you give me instruction document?
Where i can find it?

**Comment by endofthepain** [comment]
@top1st  have u check secret.yml on config/ folder i setup my twillio api on there

**Comment by gfedorenko** [comment]
@top1st 
Barong uses Twillio to send sms. You need to set up Twillio account and update configs with your test or production credentials(id, token, phone number).

**Comment by top1st** [comment]
otpauth://totp/Barong:admin@barong.io?algorithm=SHA1&digits=6&issuer=Barong&period=30&secret=C33TWEKCFAKG4ADQVVWSEAX3I2IFGTUF
I have enabled two factor auth 
when i click enable two factor auth link i can see this link 
what is this?
![image](https://user-images.githubusercontent.com/23559697/37920552-bfea424e-3159-11e8-8317-e44caf3c4761.png)
