### ISSUE TITLE
Add API for manage labels

### ISSUE THREAD

**Issue by maksim-litvinov** [rubykube/barong#306]
We need CRUD actions to manage labels:
API must follow REST.

Label is a resource with next fields:
- key: `string`
- value: `string`
- scope: `['public', 'private']`

Example of labels:

- email: verified
- color: blue
- size: 42

#### Public scope

Tags with public scope can be created from API
and update they are 100% owned by the user.

#### Private scope

Private tags can be only created from Barong admin panel
they are READ ONLY from api.

**Comment by mitjok** [comment]
@maksim-litvinov could you reflect this slack post of @mod in this ticket
https://rubykube.slack.com/archives/C8XSU8WJW/p1522426201000507

**Comment by maksim-litvinov** [comment]
@mitjok I updated scopes

**Comment by maksim-litvinov** [comment]
Merged to master
