### ISSUE TITLE
File uploaded, but system message is "error" type instead of "success"

### ISSUE THREAD

**Issue by DanielHawkins** [rubykube/barong#310]
413 Request Entity Too Large
or 
We're sorry, but something went wrong
errors

But then during next visit shows:
Pending compliance officer approval

**Comment by maksim-litvinov** [comment]
I think this issue when file is too large. It should print more user friendly error like "Max upload file size is N mb"

**Comment by andreymakovenko** [comment]
@DanielHawkins reproducing steps needed

**Comment by HafeezRai** [comment]
You can define file size in upload_uploader.rb in uploader folder like this
def size_range
          3256...5748
  end
Than it will show file size error

**Comment by pkucherenk0** [comment]
@maksim-litvinov I have the same issue with latest  test Stage.
![selection_401](https://user-images.githubusercontent.com/38254545/41536860-799d01da-730f-11e8-9574-5fa5709805ab.png)
I have found that user will be able to upload the file up to 10M in size before getting an error.
![selection_402](https://user-images.githubusercontent.com/38254545/41536968-c90e58c2-730f-11e8-889b-06e552309f5d.png)
But the actual size of accepted pictures is lower.

The API request failing as well, under 1.5M
![image](https://user-images.githubusercontent.com/38254545/41538843-df4da962-7314-11e8-9502-4028da929a0d.png)

Also with the API we can send files from .txt to .exe
![image](https://user-images.githubusercontent.com/38254545/41538989-4a75db9c-7315-11e8-9e47-bc456b50d2eb.png)
