### ISSUE TITLE
"Phone is invalid" with international code

### ISSUE THREAD

**Issue by andreymakovenko** [rubykube/barong#313]
![screenshot-2018-4-3 barong](https://user-images.githubusercontent.com/15743844/38253667-e375bf8e-375f-11e8-8d1b-9f3a8f78d036.png)
It works fine without "+" in country code, but placeholder for this field is "+1", what makes some misunderstanding

**Comment by andreymakovenko** [comment]
UPDATE: Issue appears at Mozilla Firefox 59.0.
works fine with Chromium 65.0.3325.162

**Comment by maksim-litvinov** [comment]
Checked with latest version and firefox. It works
