### ISSUE TITLE
Unable to receive SMS to +38(091)XXX-XX-XX

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#322]

**Comment by andreymakovenko** [comment]
What browser are you using?

**Comment by yivo** [comment]
@andreymakovenko How is this related to the problem?

**Comment by yivo** [comment]
I am able to submit phone, request is issued but no SMS...

**Comment by andreymakovenko** [comment]
@yivo oh, I see
I thought it can be related to https://github.com/rubykube/barong/issues/313
