### ISSUE TITLE
Use fog-google 1.3.3

### ISSUE THREAD

**Issue by ashanaakh** [rubykube/barong#342]

**Comment by andreymakovenko** [comment]
Why?

**Comment by ashanaakh** [comment]
@andreymakovenko, can you try to update gem and use google service account instead of keys?
We can't automate usage of this `accessKey` and `secretKey`.

**Comment by andreymakovenko** [comment]
@ashanaakh please, check existing issues before crating the new one.
https://github.com/rubykube/barong/issues/320
I will close your issue

**Comment by ashanaakh** [comment]
Cool, but they are not the same! '

**Comment by andreymakovenko** [comment]
@ashanaakh what do you mean? who said what we should use fog?

**Comment by ashanaakh** [comment]
I mean we need support for service account a soon as possible, doesn't matter how you will do it 😄

**Comment by maksim-litvinov** [comment]
@ashanaakh as I understand we are going to move on https://www.minio.io AWS S3 comnatible storage
