### ISSUE TITLE
Add ability to run without Vault and show warning

### ISSUE THREAD

**Issue by vshatravenko** [rubykube/barong#346]
There should be an ability to mock Vault and make 2FA disabled in Barong(e.g. for automated deployments)

**Comment by jdowning100** [comment]
Was there ever a resolution to this? I need a way to automatically approve users, without 2FA (it's not necessary)

**Comment by maksim-litvinov** [comment]
@jdowning100 you can approve users regardless of 2FA. 
2FA is optional. We don't force people to enable it and it doesn't touch any platform limits

**Comment by jdowning100** [comment]
@maksim-litvinov yes I understand, but approval is not automated, and if I have a large number of registrations manually approving them will take too long. It seems like barong doesn’t support automation for approvals so I will just write a script.
