### ISSUE TITLE
User should be notified if he was rejected by admin 

### ISSUE THREAD

**Issue by TasyaBykova** [rubykube/barong#347]
Setup: 
1. Sign up as a new user1 to Barong (3 levels of verification)
2. Go to Admin panel as an admin 

Steps to reproduce: 
1. Go to Profile in Admin panel  
2. Find  user1 profile 
3. Select 'Rejected' state for User1

Actual Result: 
User1 doesn't know that he was rejected. When he logins to the system, he sees the following message 'Signed in successfully. Pending compliance officer approval. Signed in as 'email''

Expected Result: 
User should be notified if he was rejected by admin. For example, user should receive email notification. When rejected user is trying to login, he will see that he was rejected and the reason of the rejection.

**Comment by andreymakovenko** [comment]
When new user is rejected during level 3 confirmation by Barong admin, system stills tells user "Pending compliance officer approval", no notification that he is rejected
When approved user is rejected he still sees success message and no level is changed

**Comment by maksim-litvinov** [comment]
Implemented here https://github.com/rubykube/barong/pull/372
