### ISSUE TITLE
ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by martianatwork** [rubykube/barong#349]
Extracted source (around line #195):

`
def handle_unverified_request
    raise ActionController::InvalidAuthenticityToken
end
      end
    end
`

**Comment by maksim-litvinov** [comment]
I don't understand the description.

**Comment by martianatwork** [comment]
Hey, this error is fixed, If i get this error again i will share the logs and proper details.

**Comment by martianatwork** [comment]
Is your vault server up and listening on 8200 also add `0.0.0.0 vault` to your /etc/hosts on host machine

**Comment by frivolous106** [comment]
@martianatwork 
Thank very much for you.
I run my vault server as port 8200, and added 0.0.0.0 to the /etc/hosts.
I am trying to login with barong.
Now i have admin account.
I successfully did sign in in Barong, but after signining barong, cannot return my Peatio platform.
I installed Barong and Peatio as separate server.
This is the issues log.
![image](https://user-images.githubusercontent.com/34869694/40616136-820b3f22-6292-11e8-93fe-cf684bec4205.png)
![image](https://user-images.githubusercontent.com/34869694/40616146-92eb82c0-6292-11e8-87b2-b52b34f003bb.png)
![image](https://user-images.githubusercontent.com/34869694/40616162-a37a62d2-6292-11e8-8edf-3e5000422e89.png)
![image](https://user-images.githubusercontent.com/34869694/40616253-051dce0c-6293-11e8-8132-c32e81ba50d7.png)

Please solve my issue.

**Comment by frivolous106** [comment]
Fixed, Thank anyway!

**Comment by AnkitRathore175** [comment]
Hi,
I m getting same issue, when clicks on submit button of login page on  ***1-9-stable*** branch.
Any suggestion?
FYI, I m using workbench on public IP
Thanks
