### ISSUE TITLE
The Gmail address registration issue 

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/barong#399]
The dots dosnt matter in the Gmail address:
https://support.google.com/mail/answer/7436150?hl=en
This is giving a possibility to registration a lot of account on a single email address.
Simply register an account, with a dot (name.surname@gmail.com), and start registering accounts on Barong with a different dots placement, like n.ame.surname@gmail.com, n.a.m.e.s.u.r.n.a.m.e@gmail.com or namesurname@gmail.com. You will get the verification email for each one of them to the original name.surname@gmail.com.
![selection_152](https://user-images.githubusercontent.com/38254545/39174760-3d61a2fe-47b1-11e8-88a0-2309238d297d.png)
![selection_153](https://user-images.githubusercontent.com/38254545/39175564-5b8092fc-47b3-11e8-941d-66676146efae.png)

**Comment by dutchakdev** [comment]
also u can use name.surname+freetext@gmail.com

**Comment by maksim-litvinov** [comment]
I investigated it and decide to close it. Technically user can register multiple accounts but it does not cause any security issues. Thief can't login and verify unless he has access to original email.
Users need to enable 2FA and secure email accounts to prevent any hacking
