### ISSUE TITLE
API, phone step can be skipped and get level 3 user

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/barong#402]
STR:

1. create a account 
2. see that it is requesting a phone number
3. use Barong API to add profile info:
 -first_name
 -last_name
 -dob
 -address
 -postcode
 -city
 -country
4. use Barong API to add document:
 -doc_expire
 -doc_type
 -doc_number
 -upload

5. as an admin user go to admin panel
6. find the request for document approval (from previous steps)
7. approve it

8. come back to the recently created account 
9. see that your status is approved now
10.  proceed to the front and see that you have level 3

Expected: The user should not be able to skip the phone verification step.

**Comment by maksim-litvinov** [comment]
We added  dynamic levels. Need to re-test

**Comment by andreymakovenko** [comment]
Fixed by dynamic levels feature
