### ISSUE TITLE
Deleting an user in Barong did not delete the user's phone or should user deletion be allowed?

### ISSUE THREAD

**Issue by NQA1** [rubykube/barong#437]
Deleting an user in Barong did not delete the user's phone or should user deletion be allowed?
Deleting a user in barong should clear off all the user's meta data such as phone number and the uploaded docs. However, its not removing the user's phone and docs and there the phone number could not be reused.

This would mean all user's history in peatio gets deleted as well. If this is not desirable, then there should be no way a user could be deleted (or accidetally deleted) in barong.

**Comment by maksim-litvinov** [comment]
We can use [paranoia gem](https://github.com/rubysherpas/paranoia)
This gem allows to mark model as deleted and doesn't realy destroy it

**Comment by Sambusik** [comment]
Under GDPR law, the user must be allowed to delete their account.
