### ISSUE TITLE
API Key expiration

### ISSUE THREAD

**Issue by sergii-savchenko** [rubykube/barong#456]
Please, give possibility to generate API Keys without expiration.

`https://github.com/rubykube/barong/blob/feature/api_keys/app/models/api_key.rb`

On the other hand we need to have `api` to:
* revoke` api key`. 
* `api key` status (checked each request from peatio or applogic)

**Comment by sergii-savchenko** [comment]
1. As a user I can access Barong, click on "Generate new Secret/API key", select needed scopes, and activate API key using MFA. 
2. As a user I can access Barong, click on "Revoke Secret/API key", select needed scopes, and deactivate API key using MFA. 
3. All calls made with generated Secret/API key MUST be validated using revocation endpoint of Barong

**Comment by maksim-litvinov** [comment]
We don't need that. API key has not expiration time. Session associated with api key has expiration time.
