### ISSUE TITLE
Changing already created labels scope from private to public is not changing the level of users account.

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/barong#476]
STR:
 
1. Go to the Barong admin panel.
2. Find account with labels in scope private and level that goes with it.
Example:
![selection_245](https://user-images.githubusercontent.com/38254545/40128788-358f3dca-593b-11e8-8eb3-f4eb78a162e1.png)
3. Click on the email address to get to user profile.
4. Change labels with private scope to public.

Result: The level of user was not changed .
![selection_244](https://user-images.githubusercontent.com/38254545/40128935-a298fc6c-593b-11e8-88b5-2557e7ec8c46.png)
Expected: The level of user should decrees according to current existing private labels.

**Comment by maksim-litvinov** [comment]
Fixed
