### ISSUE TITLE
Ability to generate API key pair server-side

### ISSUE THREAD

**Issue by sergii-savchenko** [rubykube/barong#496]
Users, who can't generate key pairs for API should have ability to generate server-side without saving private key, just returning it for POST call. 

Generation of  Key pair must require scope and 2fa in call

**Comment by maksim-litvinov** [comment]
I'm not sure why do we need it.
We can generate keys from frontend using for example this library https://www.npmjs.com/package/pem or that one https://github.com/digitalbazaar/forge
