### ISSUE TITLE
Bug with extra "0" in phone number 

### ISSUE THREAD

**Issue by pkucherenk0** [rubykube/barong#499]
It is expected to allow verify only one unique phone number per platform.
For example number +44 7418084106 can receive sms until it be verified with code from sms, than if you will try to create a new account with same number you will get an error that will inform you about this number have been taken already.
![selection_301](https://user-images.githubusercontent.com/38254545/40720140-6aed1468-641e-11e8-9572-0718baeefffb.png)

But, if you will add "0" between country code and a phone number, like: +44 0 7418084106, it will be count as a new unique number and sms with verification code will be send to +44 7418084106.
![selection_302](https://user-images.githubusercontent.com/38254545/40720147-706ef58c-641e-11e8-9774-0cf12b280fa3.png)

**Comment by Liudmyla-S** [comment]
After verification valid Phone number enter the same number with '0'  between country code and a phone number, f.ex. +39 3512556080 and +39 0 512556080.
Expected result: System does not accept Phone number with '0' like unique.
Actual result: By entering Phone number with code +39 (Italy) system accepts number with '0' like unique and displays message : 'Code was sent successfully'

![code](https://user-images.githubusercontent.com/40030651/41102599-f8ff3680-6a6f-11e8-8a17-30ef7ea704a6.JPG)

But we did not receive code. Also Phone number with '0' will be written in Account profile in BE. 
This situation will occur by verification number in FE same like by API.
Note: It does not work with Germany phones.

![phone_22](https://user-images.githubusercontent.com/40030651/41102899-97805e38-6a70-11e8-92d7-65c69a3e644b.jpg)
