### ISSUE TITLE
Omission in the passport verification flow

### ISSUE THREAD

**Issue by Lubyvyi** [rubykube/barong#500]
how can I understand that the user has already uploaded a passport and he is waiting for verification or he did not download anything?
for example there is a form of verification in which I passed the phone number check and sent the passport for verification and closed the modal window. After a while I again open this form and it should open on the place where the user last time finished. How can I understand that he has already uploaded the passport and it is just waiting for verification?

**Comment by maksim-litvinov** [comment]
When user uploads document successfully, barong creates private label with key "document" and value "pending". Frontend can check it with request `GET /v1/labels/document` https://github.com/rubykube/barong/blob/master/docs/index.md#getv1labelskey
