### ISSUE TITLE
On document varification user Level does not update to 3

### ISSUE THREAD

**Issue by HafeezRai** [rubykube/barong#503]
Hi when i verify user's document barong does not update user level to 3 it is remained 2 is this is bug or any issue with me

**Comment by maksim-litvinov** [comment]
We need to remove `indentity:verified` for default barong

**Comment by maksim-litvinov** [comment]
To fix the issue with levels, you need to recreate levels table
In Rails console run `ActiveRecord::Base.connection.execute('TRUNCATE TABLE levels;')`

In terminal run bundle `exec rake db:seed`
