### ISSUE TITLE
Wrong customer ID or password,please try again.

### ISSUE THREAD

**Issue by fouvy** [rubykube/barong#509]
Peatio auth with google is Ok, but auth with barong got wrong message: "Wrong customer ID or password,please try again.", using 1-8-stable.

**Comment by frivolous106** [comment]
Hi, @fouvy 
Please check your callback url.

**Comment by fouvy** [comment]
I have solved this, it's nginx with passenger issue.

**Comment by A4Logic** [comment]
What was issue can you explain please

**Comment by samsoft00** [comment]
Please how do you resolve the above issues?

**Comment by fouvy** [comment]
Dear @samsoft00 
I use thin with nginx to solve this problem. there are some issues that passenger with nginx. I don't know why.

**Comment by samsoft00** [comment]
Hi @fouvy, been on this issues for weeks, tried to follow some documentation online about Nginx and thin but unfortunately, nothing works, still faced with the same error, can you please give me some hint on how to set this up please? Thanks
