### ISSUE TITLE
Ability to let frontend to know that account has enabled 2FA

### ISSUE THREAD

**Issue by maksim-litvinov** [rubykube/barong#520]

**Comment by mod** [comment]
I suggest the simpleLogin api return an custom error code
if login and password is valid, we return a error code like 543

error 543 means OTP required.
you need to repost login, password with otp

**Comment by maksim-litvinov** [comment]
I would like to use 403 instead of custom code. It's common practice to use that code. https://httpstatuses.com/403

"If authentication credentials were provided in the request, the server considers them insufficient to grant access"
