### ISSUE TITLE
Ability to fetch my login history from API

### ISSUE THREAD

**Issue by mod** [rubykube/barong#524]
device_activity table
- account_id
- device_id (UUID)
- user ip
- proxy ip
- country
- os
- user agent
- status
- created_at

What do we record:
- basic login success (otp disabled)
- known device login success
- new device login success (with otp)
- device expired login success (with otp)
- login failed (password)
- login failed (otp)
- logout
- otp reset
- otp enable
- password forgot
- password change

| *story* | column action | column otp | column device_expire | column result |
|--------|--------|--------|--------|--------|
| basic login success (otp disabled) | login | na | NULL | success |
| known device login success | login | enabled | 2018-07-23 23:42:44 | success |
| new device login success (with otp) | login | provided | no | success |

- device expired login success (with otp)
- login failed (password)
- login failed (otp)
- logout
- otp reset
- otp enable
- password forgot
- password change

```
Google show:
Linux
Browser	
Chrome 66.0
Kyiv, Ukraine - Just now
Last location used	
Kyiv, Ukraine - 20 minutes ago
```

**Comment by ec** [comment]
First part with activity on session already in master
https://github.com/rubykube/barong/commit/e3b44ae59e6fd9a1e32dd8d76030baa7b9c246de

**Comment by ec** [comment]
Improvements on coverage already in master
fc02c8c10592032d7df4bb2c93d8c851c604e74b
