### ISSUE TITLE
API allows Login Without 2FA for a 2FA Enabled Account

### ISSUE THREAD

**Issue by sramsden** [rubykube/barong#526]
To recreate, simply enable 2FA for an account then use the API to login.

Currently `UserApi::V1::Sessions` does not expect a 2FA code.
(I am testing against version 1.8)

**Comment by maksim-litvinov** [comment]
It has already implemented at https://github.com/rubykube/barong/pull/522 waiting for qa

**Comment by maksim-litvinov** [comment]
Fixed as 1.8.15 release
