### ISSUE TITLE
How to get BARONG_CLIENT_ID, etc?

### ISSUE THREAD

**Issue by Coding-Jewelry** [rubykube/barong#529]
Hi.
Now I am trying to install Rubykube Peatio with Barong Oauth.

I have already installed Barong server, but I am not sure how I can get Barong parameters, like...

BARONG_CLIENT_ID,
BARONG_CLIENT_SECRET,
BARONG_DOMAIN,
BARONG_OAUTH2_REDIRECT_URL
...

Please let me know if you have any idea about it.
Thank you.

**Comment by ec** [comment]
```BARONG_CLIENT_ID``` its id of the application you should create in barong admin panel
```SECRET``` listed here as well.
```BARONG_DOMAIN``` its domain on what you are hosting barong
```BARONG_OAUTH2_REDIRECT_URL``` url where barong should redirect after successful sign in through peatio
