### ISSUE TITLE
"Sign In With Barong" button is not shown

### ISSUE THREAD

**Issue by Coding-Jewelry** [rubykube/barong#530]
Hi.

Now I am trying to install Rubykube Peatio. 
Actually I did installed it already, and you can check it:  http://35.226.198.87

But I cannot see "Sign In With Barong" button to register/login.
How can I see the button?
Please let me know if you have any idea about it.

I appreciate you.

**Comment by ec** [comment]
Please follow the guidelines of peatio.
Problem is in the configurations.
Without any additional info we cant help you.

You can try to describe your problem at https://discuss.rubykube.io
