### ISSUE TITLE
Reset password link with CUSTOM URL

### ISSUE THREAD

**Issue by vadym-poberezhny** [rubykube/barong#538]
When user reset password(security/reset_password method), he receives an email with link to barong site.
Need to have possibility to put custom URL, for example https://domain.com/resetpassword.

It could be the additional parameter in security/reset_password method.

**Comment by maksim-litvinov** [comment]
env variable FRONTEND_DOMAIN is your solution. https://github.com/rubykube/barong/blob/master/app/helpers/view_helper.rb#L33
