### ISSUE TITLE
JWT Tokens

### ISSUE THREAD

**Issue by ZohairZaman** [rubykube/barong#546]
I went through the docs and was able to generate a JWT token as outlined here:
https://github.com/rubykube/barong/blob/master/docs/api/authenticating_in_management_api_v1.md

My response is something like:
`{"payload":"eyJ..4In19","signatures":[{"protected":"..UzI1NiJ9","header":{"kid":"backend-1.sample.io"},"signature":"Z4cTn19J713NZl6Xd8rFqp9CDeGYSOsqrf2UoJPwRPnXf_AC0eRuD6KVjtqRBCuGt1mCl-NiafuLJaEdc8SpH0mw3IY_gm2-8YvNcFW..buCb1p6n...XQRPtnWK-NM9D1Jp45e..HOfOozVUS9bl-b47uj..6d7jMEbdwu-eMMYp4jPKld9P.._v30mDQw_kj5U44W5m0B3wt..ACRpYtcu5..elsJ7dr_dg"}]}
`
Once I have this, I am not really sure how to utilize this for the API requests.
For any given API request that I try to make, I get: 
"The access token is invalid"

Even though according to the docs some of the API requests do not require any form of authorization whatsoever (for example get api_keys with the google authenticator code). However, I have noticed that the docs are almost always incorrect, so I will just assume that the token is required for pretty much all of the requests. My issue is, with the output as detailed above, how exactly am I supposed to get the serialised token? It seems to be of the format xxx.xxx.xxx, which is clearly nowhere in the response.

**Comment by ZohairZaman** [comment]
@maksim-litvinov seems like you are consistently helping with issues on this repo. Would really appreciate your thoughts

**Comment by maksim-litvinov** [comment]
@ZohairZaman  You can use this token for this api only https://github.com/rubykube/barong/blob/1-8-stable/docs/api/management_api_v1.md not for user api.
For user api you should auth with your email:password with sessions api https://github.com/rubykube/barong/blob/1-8-stable/docs/api/api.md#postv1sessions

**Comment by ZohairZaman** [comment]
@maksim-litvinov Thanks. I was able to successfully get the bearer token needed for making user API requests.
However, I have a question. It seems like once I have this token, I need to generate API keys via this token. I am using the post endpoint to do this, and can do so successfully.
My question is, within the parameters of the api keys endpoint, there is a public key field. What exactly should this be? Similarly, what exactly does this step mean:

Sign request with your private key

Are these the same public and private keys that are within the management_api_v1.yml? Currently, I am able to generate api keys with any random public key, but when it comes to generating the jwt for peatio, it feels on the decoding step, which tells me that the public key needs to be something specific. Could you please explain this process a little more, as I believe there are some gaps in the documentation

**Comment by samsoft00** [comment]
@rxx thanks, helpful information, please what's the endpoint to register new user?

**Comment by ec** [comment]
@samsoft00 its ```POST /v1/accounts```
https://github.com/rubykube/barong/blob/1-8-stable/docs/api/api.md#postv1accounts
