### ISSUE TITLE
Social Sign In/Up Support

### ISSUE THREAD

**Issue by vadym-poberezhny** [rubykube/barong#547]
Add possibility to sign in/up with social networks.

**SING UP**
Right now for sign up we use **/accounts** method with email and password parameters
for social sign up we need next parameters
**provider**: name of social network, for example 'facebook'
**providerUserId**: - user id in social network. For example for facebook - 10100133067994469
**providerAccessToken**
**email**
**password**
Once, backend receive above data, verify the providerAccessToken, store provider and providerUserId for new user. Keep in mind that one user can have many providers, for example 'facebook', 'google'...

**SING IN**
Right now for sign in we use **/sessions** method with **email** and **password** as parameters
For social login we need next parameters:
**provider**: name of social network, for example 'facebook'
**providerUserId**: - user id in social network. For example for facebook - 10100133067994469
**accessToken**
So for this you can extend **/sessions** method or create a new one.
Once login is called, check providerAccessToken and find user by providerUserId 

**BACKEND**
on the backend you need to keep secret key for each social network to be able to connect to appropriate social application.

**Comment by Sambusik** [comment]
I strongly doubt Social Logins will be used by end users to register at a Cryptocurrency exchange

**Comment by martianatwork** [comment]
@Sambusik I think we should implement this because barong can be used in other applications as well in future.
