### ISSUE TITLE
Document Upload - We're sorry, but something went wrong. - ArgumentError ( is not a recognized provider)

### ISSUE THREAD

**Issue by TheHolyRoger** [rubykube/barong#555]
Hello, upon upload of documents to Barong for the ID verification, I receive a:

> We're sorry, but something went wrong.

Here's my Barong log:

`
INFO -- : [] Started POST "/documents" for XXX at XXX
INFO -- : [] Processing by DocumentsController#create as HTML
INFO -- : []   Parameters: {"utf8"=>"✓", "authenticity_token"=>"XXX",
 "document"=>{"upload"=>#<ActionDispatch::Http::UploadedFile:0x0000555dc9fb1c98 @tempfile=#<Tempfile:/tmp/RackMultipart20180625-1-1bvpxh3.png>, @original_filename="bcrap.png", @content_type="image/png", @headers="Content-Dispo
sition: form-data; name=\"document[upload]\"; filename=\"bcrap.png\"\r\nContent-Type: image/png\r\n">, "doc_type"=>"Passport", "doc_expire"=>"XXX", "doc_number"=>"XXX"}, "commit"=>"Submit"}
DEBUG -- : []   Account Load (0.4ms)  SELECT  'accounts'.* FROM 'accounts' WHERE 'accounts'.'id' = 2 ORDER BY 'accounts'.'id' ASC LIMIT 1
DEBUG -- : []    (0.4ms)  BEGIN
DEBUG -- : []   SQL (0.4ms)  INSERT INTO 'documents' ('account_id', 'upload', 'doc_type', 'doc_number', 'doc_expire', 'created_at', 'updated_at') VALUES (2
, 'bcrap.png', 'Passport', 'XXX', 'XXX', 'XXX', 'XXX')
DEBUG -- : []    (1.4ms)  ROLLBACK
INFO -- : [] Completed 401 Unauthorized in 9ms (ActiveRecord: 2.6ms)
FATAL -- : []   
FATAL -- : [] ArgumentError ( is not a recognized provider):
FATAL -- : []   
FATAL -- : [] app/controllers/documents_controller.rb:13:in 'create'
`

**Comment by maksim-litvinov** [comment]
What is your fog privider? I may cause issues https://github.com/rubykube/barong/blob/master/config/initializers/carrierwave.rb

**Comment by TheHolyRoger** [comment]
Thanks for your quick response! I'm using local, does that not work?

**Comment by TheHolyRoger** [comment]
Works fine using google, i guess local isn't implemented?

**Comment by maksim-litvinov** [comment]
local is only for development

**Comment by AnthonyRex** [comment]
> local is only for development

I am using barong 
I am not using local, I am using in production

I was trying to add barong but facing the same issue 
ArgumentError ( is not a recognized provider):
----------
log
I, [2018-10-12T00:45:19.570960 #24618]  INFO -- : [16761cb3-63a1-43f8-92fa-3de5e57482b3] Completed 500 Internal Server Error in 12ms (ActiveRecord: 4.2ms)
F, [2018-10-12T00:45:19.571575 #24618] FATAL -- : [16761cb3-63a1-43f8-92fa-3de5e57482b3]   
F, [2018-10-12T00:45:19.571604 #24618] FATAL -- : [16761cb3-63a1-43f8-92fa-3de5e57482b3] ArgumentError ( is not a recognized provider):
F, [2018-10-12T00:45:19.571621 #24618] FATAL -- : [16761cb3-63a1-43f8-92fa-3de5e57482b3]   
F, [2018-10-12T00:45:19.571638 #24618] FATAL -- : [16761cb3-63a1-43f8-92fa-3de5e57482b3] app/controllers/documents_controller.rb:17:in `create'
---
    config.fog_directory = Rails.application.secrets.storage_bucket_name
  elsif '**Barong**'.casecmp(Rails.application.secrets.storage_provider) == 0
    config.fog_provider = 'fog/**barong**'
    config.fog_credentials = {
      provider: '**Barong**',
      aws_access_key_id: Rails.application.secrets.storage_access_key,
      aws_secret_access_key: Rails.application.secrets.storage_secret_key,
      region: Rails.application.secrets.storage_region
    }
    config.fog_directory = Rails.application.secrets.storage_bucket_name
  else
    config.storage :file
  end
end
--
I am sure there must be some changes somewhere else , but where ? 

why can't include barong while everything else is configured to use barong  ?
