### ISSUE TITLE
(barong) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

### ISSUE THREAD

**Issue by melmali2828** [rubykube/barong#559]
Hi,

![image](https://user-images.githubusercontent.com/14098096/42324443-e01fe972-806b-11e8-98b6-a316837d07d9.png)

![image](https://user-images.githubusercontent.com/14098096/42324463-f17b04ea-806b-11e8-93ff-96a345494e09.png)

![image](https://user-images.githubusercontent.com/14098096/42324471-fcedaaee-806b-11e8-8531-d6ba963e25d0.png)

Log:
![image](https://user-images.githubusercontent.com/14098096/42324495-0891f1fc-806c-11e8-90b8-609f14e7d03b.png)

**Comment by maesitopi** [comment]
@melmali2828 have you created a new keypair and assigned them in barong in the secrets? 

https://github.com/rubykube/barong/blob/master/docs/api/authenticating_in_management_api_v1.md

**Comment by melmali2828** [comment]
no, Is it necessary to do them?

**Comment by ec** [comment]
Try to follow public guidelines on how to setup configurations or try workbench.
Problem clearly comes from configs
