### ISSUE TITLE
The server Barong(1.8-stable) doesnot send sms code at all.

### ISSUE THREAD

**Issue by frivolous106** [rubykube/barong#562]
I have set Twilio config info in secret.yml.
I am using with Twilio full account.
I confirmed whether the info was set in code exactly.
Also on Twilio dashboard page, when requesting the message to the phone number, i receive the message on my phone.
But i cannot receive any sms code from Barong.
I am using Barong 1.8-stable.
The rubykube peatio and barong disappoints me more and more.
I am waiting this solution now.

**Comment by frivolous106** [comment]
I fixed this issue by myself.
The barong code has a error.

**Comment by ianeinser** [comment]
@frivolous106 have you successfully configured email verification? mind sharing to us?
