### ISSUE TITLE
User session is maintained when signing out from 1 of the 2 apps

### ISSUE THREAD

**Issue by umaimehm** [rubykube/barong#571]
Since both Barong and peatio are sharing cookie for login information, the user has to be signed out individually from both Barong and Peatio.
Signout from one application does not sign out the user and shows incorrect information to the second user signing on the same browser.

Flow:
1. User1 is signed in through barong. Everything looks okey.
2. User1 opens Peatio and checks their profile information.
3. User1 signs out of barong (but does not click Exit on Peatio )
4. Admin (or normal User2) successfully signs into barong.
5. Open Peatio and it shows profile of User1.

"The same will hold true if user signs out of Peatio and does not sign out of Barong".

workbench: master
peatio: 1-8-stable
barong: 1-8-stable

**Comment by umaimehm** [comment]
not a bug

**Comment by martianatwork** [comment]
@umaimehm Hey i think this issue still exist and this should be an open issue. Correct me if it fixed.

**Comment by InfraExEric** [comment]
We are currently using js to sign out of both simultaneously.

**Comment by AnthonyRex** [comment]
> We are currently using js to sign out of both simultaneously.

I am having issues try to do that.  do you have any sample of  this js ?

**Comment by legends420** [comment]
Any fix for this? sample of the JS maybe?
