### ISSUE TITLE
Remove/clean session API method

### ISSUE THREAD

**Issue by vadym-poberezhny** [rubykube/barong#577]
Currently, we have /sessions API method for starting user session, but no method for removing/cleaning it. Or maybe there are some alternatives?

It's needed at least for a web. There is a case, the jwt token can be used again after user logout.

**Comment by m-an** [comment]
@vadym-poberezhny you can revoke access token using doorkeeper endpoint

**Comment by samsoft00** [comment]
Please guys, where can i find documentation for Barong API authentication please.

**Comment by m-an** [comment]
@vadym-poberezhny https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples#post---oauthrevoke
