### ISSUE TITLE
User documents are publicly visible by default (carrierwave / fog)

### ISSUE THREAD

**Issue by CorentinGC** [rubykube/barong#581]
https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Secure-uploaded-file-in-S3-and-make-it-only-accessible-by-supplying-secret-token%3F

**Comment by mazlumtoprak** [comment]
The suggested solutions works for google cloud storage. Pasted the snippet

```
def fog_public
    false
  end

  def fog_authenticated_url_expiration
    1.minutes # in seconds from now,  (default is 10.minutes)
  end
```

into app/uploaders/upload_uploader.rb

**Comment by ec** [comment]
#672 #673 follow the PRs

**Comment by ec** [comment]
#672 #673 merged
