### ISSUE TITLE
Error During Compilation

### ISSUE THREAD

**Issue by laugh26** [rubykube/barong#584]
Whenever i run bundle exec rake db:create db:migrate, i end up getting the following error
rake aborted!
NoMethodError: undefined method `tr' for nil:NilClass
Did you mean?  try
/practice/barong/config/initializers/doorkeeper.rb:145:in `rescue in block (2 levels) in <top (required)>'
/practice/barong/config/initializers/doorkeeper.rb:142:in `block (2 levels) in <top (required)>'
/practice/barong/config/initializers/doorkeeper.rb:141:in `tap'

**Comment by IbrahimSerhat** [comment]
Hi @laugh26 ,

It's about missing secrets.

You have to define following contents to your env file our bashrc somethink like that :           
     SECRET_KEY_BASE
     DEVISE_SECRET_KEY
     JWT_SHARED_SECRET_KEY

You can write me if you cant.

My email is ibrahimserhatyilmaz@gmail.com

**Comment by ec** [comment]
Problem in the configurations. You are missing some config files or have a wrong one.
Project builds pretty well on current stage
