### ISSUE TITLE
Rework Auth API documentation

### ISSUE THREAD

**Issue by kovetskiy** [rubykube/barong#602]
https://github.com/rubykube/barong/blob/master/docs/api/api.md#postv1securityrenew

For some reason Auth API's docs look very ugly, instead of beautiful headers like in Management API:
```
POST /management_api/v1/otp/sign
Summary: Sign request with barong signature
```

in Auth's API we have `postV1SecurityGenerateQrcode`, it should be reworked and must have the same format as in Management API.

**Comment by rxx** [comment]
I think both formats of API are ugly. But first one is ugly only in text variant. It's format for server rendered docs and it's awesome. The problem that we have no public api doc server

**Comment by ec** [comment]
Postponed
