### ISSUE TITLE
Markup issues

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#84]
<img width="1280" alt="screen shot 2018-01-31 at 3 08 25 pm" src="https://user-images.githubusercontent.com/7421323/35625088-b6ecac26-0699-11e8-8e29-7113c57a65cb.png">

**Comment by ashanaakh** [comment]
Now it look like that:
![image](https://user-images.githubusercontent.com/15674738/36060558-c8ee5c54-0e54-11e8-9765-6d0ed83a17a7.png)

**Comment by ashanaakh** [comment]
![image](https://user-images.githubusercontent.com/15674738/36062851-1be373fe-0e7d-11e8-9634-cdf1ebadee27.png)

**Comment by ashanaakh** [comment]
`/phones/new`

![image](https://user-images.githubusercontent.com/15674738/36062859-38c306ec-0e7d-11e8-8a4d-d9f16042af67.png)

**Comment by gfedorenko** [comment]
Fixed
