### ISSUE TITLE
There is no SMS throttling (possible to send as many SMS I as want)

### ISSUE THREAD

**Issue by yivo** [rubykube/barong#89]

**Comment by yivo** [comment]
![photo_2018-01-31_18-10-30](https://user-images.githubusercontent.com/7421323/35633504-1550cd66-06b2-11e8-901b-cf9d70cf6c2e.jpg)
![photo_2018-01-31_18-10-47](https://user-images.githubusercontent.com/7421323/35633505-15afc046-06b2-11e8-9e28-26c78d117286.jpg)

**Comment by ashanaakh** [comment]
@gfedorenko I tested it, seems like fixed, isn't it?

**Comment by yivo** [comment]
@ashanaakh @gfedorenko Still not fixed.

![image](https://user-images.githubusercontent.com/7421323/36972212-f93ef9e8-2076-11e8-95c5-1d34804aa85c.png)

**Comment by lizhuomeng71** [comment]
for throttling on API, I suggest APP that use the barong API to use an Third Party API Gateway Layer, this way barong does not have to worry about considering the throttling logic and other logic as well, those logic can be hand to API Gateway. like the AWS API Gateway
